#!/bin/bash

# Script de démonstration pour ft_irc

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║           GUIDE DE TEST - ft_irc SERVER                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${GREEN}✓ Compilation réussie${NC}"
echo -e "${GREEN}✓ Serveur prêt à être testé${NC}"
echo ""

echo -e "${YELLOW}COMMENT TESTER LE SERVEUR :${NC}"
echo ""

echo -e "${BLUE}Option 1 : Test avec irssi (RECOMMANDÉ)${NC}"
echo "───────────────────────────────────────────"
echo "Terminal 1 : Lancer le serveur"
echo "  ./ircserv 6667 secret123"
echo ""
echo "Terminal 2 : Se connecter avec irssi"
echo "  irssi"
echo "  /connect localhost 6667 secret123"
echo "  /nick alice"
echo "  /join #test"
echo "  /msg #test Bonjour tout le monde !"
echo "  /quit"
echo ""
echo "Installation d'irssi :"
echo "  sudo apt install irssi     # Ubuntu/Debian/Kali"
echo "  brew install irssi         # macOS"
echo ""

echo -e "${BLUE}Option 2 : Script de test automatique${NC}"
echo "───────────────────────────────────────────"
echo "  ./test_irssi.sh            # Guide complet avec irssi"
echo "  ./test.sh                  # Tests automatiques"
echo ""

echo -e "${BLUE}Option 3 : Test avec netcat (basique)${NC}"
echo "───────────────────────────────────────────"
echo "Terminal 1 : Lancer le serveur"
echo "  ./ircserv 6667 secret123"
echo ""
echo "Terminal 2 : Se connecter avec netcat"
echo "  nc localhost 6667"
echo "  Puis tapez :"
echo "    PASS secret123"
echo "    NICK alice"
echo "    USER alice 0 * :Alice Wonder"
echo "    JOIN #test"
echo "    PRIVMSG #test :Hello!"
echo "    QUIT"
echo ""
echo -e "${BLUE}Option 4 : Tests multi-clients avec irssi${NC}"
echo "───────────────────────────────────────────"
echo "Terminal 1 : Serveur"
echo "  ./ircserv 6667 secret123"
echo ""
echo "Terminaux 2-4 : Plusieurs clients irssi"
echo "  Chaque terminal lance : irssi"
echo ""
echo "  Terminal 2 (alice) :"
echo "    /connect localhost 6667 secret123"
echo "    /nick alice"
echo "    /join #general"
echo ""
echo "  Terminal 3 (bob) :"
echo "    /connect localhost 6667 secret123"
echo "    /nick bob"
echo "    /join #general"
echo ""
echo "  Terminal 4 (charlie) :"
echo "    /connect localhost 6667 secret123"
echo "    /nick charlie"
echo "    /join #general"
echo ""
echo "Tous rejoignent #general et peuvent discuter !"
echo ""
echo "Alice (opérateur du canal) peut tester :"
echo "  /topic #general Bienvenue sur notre serveur !"
echo "  /mode #general +it"
echo "  /kick bob Raison du kick"
echo "  /invite charlie #general"
echo "  /mode #general +o charlie"
echo ""

echo -e "${YELLOW}COMMANDES IRC PRINCIPALES :${NC}"
echo "───────────────────────────────────────────"
echo "  PASS <password>           - Authentification"
echo "  NICK <nickname>           - Définir votre pseudo"
echo "  USER <user> 0 * :<real>  - Définir votre identité"
echo "  JOIN <#channel> [key]     - Rejoindre un canal"
echo "  PART <#channel>           - Quitter un canal"
echo "  PRIVMSG <target> :<msg>   - Envoyer un message"
echo "  KICK <#chan> <nick>       - Éjecter (opérateur)"
echo "  INVITE <nick> <#chan>     - Inviter"
echo "  TOPIC <#chan> [:<topic>]  - Voir/modifier le sujet"
echo "  MODE <#chan> <+/-modes>   - Modifier les modes"
echo "  QUIT [:<message>]         - Se déconnecter"
echo ""

echo -e "${YELLOW}MODES DE CANAL :${NC}"
echo "───────────────────────────────────────────"
echo "  +i  - Invitation uniquement"
echo "  +t  - Topic restreint aux opérateurs"
echo "  +k  - Mot de passe du canal"
echo "  +o  - Donner privilèges opérateur"
echo "  +l  - Limiter le nombre d'utilisateurs"
echo ""

echo -e "${GREEN}Pour plus de détails, consultez :${NC}"
echo "  README.md         - Documentation principale"
echo "  TESTING.md        - Guide de test complet"
echo "  docs/PROTOCOL.md  - Détails du protocole IRC"
echo ""

echo -e "${BLUE}Bon test ! 🚀${NC}"
echo ""
